name: Run Playwright Traffic Simulation

on: [push]

jobs:
  run-playwright:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip libwoff1 libopus0 libvpx6 libevent-2.1-7 libavformat58 libavcodec58 libavutil56 libswscale5 libnss3 libxrandr2 libxcomposite1 libxdamage1 libxfixes3 libgl1 libxext6 libxi6 libxtst6 libdbus-1-3 libgtk-3-0 libdrm2 libgbm1 libasound2
        python -m pip install --upgrade pip
        pip install requests fake-useragent playwright

    - name: Install Playwright browsers
      run: python -m playwright install

    - name: Run Playwright script
      run: python auto_visitor_playwright.py
